### PR TITLE
Add instructions for setting up gitsign

### PR DESCRIPTION
**Pull request by JAORMX**
#### What does this PR do

Now that Chainguard Enforce is running on this repository, this now adds
instructions to the README.

### CODE REVIEW

**Comment by joelrebel** [comment]
@JAORMX thanks for this, although we have a separate doc for development, if you can drop these notes at the top of that doc -https://github.com/metal-toolbox/alloy/blob/main/docs/README-development.md

**Comment by JAORMX** [comment]
@joelrebel will do. Thanks!

**Review by joelrebel — DISMISSED** [review]
Looking at this again, it makes sense this is in the main README for now.

**Comment by joelrebel** [comment]
@JAORMX if theres no other changes to this, lets have it merged

**Comment by JAORMX** [comment]
I forgot about this, sorry about that.

**Review by joelrebel — APPROVED** [review]

**Pull request merged**
